name: Dependency Update

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  update-dependencies:
    name: Update NuGet Packages
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dotnet-outdated
      run: dotnet tool install --global dotnet-outdated-tool
    
    - name: Check for outdated packages
      id: outdated
      run: |
        echo "Checking for outdated packages..."
        dotnet outdated --output json > outdated.json || echo "No outdated packages or error occurred"
        
        if [ -s outdated.json ]; then
          echo "has_updates=true" >> $GITHUB_OUTPUT
          echo "Outdated packages found:"
          cat outdated.json
        else
          echo "has_updates=false" >> $GITHUB_OUTPUT
          echo "All packages are up to date"
        fi
    
    - name: Update packages
      if: steps.outdated.outputs.has_updates == 'true'
      run: |
        echo "Updating packages..."
        
        # Update packages in each project
        for project in Components/*/; do
          if [ -f "$project"*.csproj ]; then
            echo "Updating packages in $project"
            cd "$project"
            
            # Update to latest minor versions (safer than major)
            dotnet add package Microsoft.Extensions.Hosting --version "*-*" || true
            dotnet add package Microsoft.Extensions.Logging --version "*-*" || true
            dotnet add package Microsoft.Extensions.Configuration --version "*-*" || true
            dotnet add package Microsoft.Extensions.DependencyInjection --version "*-*" || true
            
            # Update test packages
            dotnet add package Microsoft.NET.Test.Sdk --version "*-*" || true
            dotnet add package xunit --version "*-*" || true
            dotnet add package xunit.runner.visualstudio --version "*-*" || true
            dotnet add package Moq --version "*-*" || true
            
            cd - > /dev/null
          fi
        done
    
    - name: Build and test after updates
      if: steps.outdated.outputs.has_updates == 'true'
      run: |
        echo "Building and testing after package updates..."
        dotnet restore
        dotnet build --configuration Release
        
        # Run core tests to ensure updates don't break functionality
        dotnet test Components/DomainTests/DomainTests.csproj --configuration Release --verbosity minimal
        dotnet test Components/StorageTests/StorageTests.csproj --configuration Release --verbosity minimal
    
    - name: Create Pull Request
      if: steps.outdated.outputs.has_updates == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          chore: Update NuGet packages
          
          Automated dependency update:
          - Updated Microsoft.Extensions.* packages
          - Updated testing framework packages
          - Verified builds and core tests pass
          
          🤖 Generated by dependency-update workflow
        title: 'chore: Automated NuGet package updates'
        body: |
          ## 📦 Automated Dependency Update
          
          This PR updates NuGet packages to their latest compatible versions.
          
          ### Changes
          - Updated Microsoft.Extensions.* packages to latest minor versions
          - Updated testing framework packages (xUnit, Moq, etc.)
          - All builds and core tests are passing
          
          ### Verification
          ✅ Build successful  
          ✅ Core tests passing  
          ✅ No breaking changes detected  
          
          ### Next Steps
          - Review the changes
          - Run full test suite
          - Merge if all tests pass
          
          ---
          🤖 This PR was created automatically by the dependency-update workflow.
        branch: chore/dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          chore

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Run security audit
      run: |
        echo "Running security audit..."
        
        # Check for known vulnerabilities
        dotnet list package --vulnerable --include-transitive > vulnerability-report.txt 2>&1 || true
        
        if grep -q "has the following vulnerable packages" vulnerability-report.txt; then
          echo "🚨 Security vulnerabilities found!"
          cat vulnerability-report.txt
          
          # Create issue for security vulnerabilities
          echo "Creating security issue..."
          echo "SECURITY_ISSUE=true" >> $GITHUB_ENV
        else
          echo "✅ No security vulnerabilities detected"
          echo "SECURITY_ISSUE=false" >> $GITHUB_ENV
        fi
    
    - name: Create security issue
      if: env.SECURITY_ISSUE == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('vulnerability-report.txt', 'utf8');
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Security Vulnerabilities Detected',
            body: `## Security Audit Report
            
            Automated security audit has detected vulnerable packages in the project.
            
            ### Vulnerability Report
            \`\`\`
            ${report}
            \`\`\`
            
            ### Action Required
            - [ ] Review the vulnerable packages
            - [ ] Update to secure versions
            - [ ] Test thoroughly after updates
            - [ ] Verify fix resolves security issues
            
            ---
            🤖 This issue was created automatically by the security-audit workflow.`,
            labels: ['security', 'high-priority', 'dependencies']
          });